version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build: 
      context: centos7
    volumes:
      - "$PWD/aws-mysql-s3-backup.sh:/tmp/awsmysql-s3-backup.sh"
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
  web2:
    container_name: web2
    image: ansible-web2
    build:
      context: jenkins-ansible/web2
    ports:
      - "8082:8082"
    networks:
      - net
networks:
  net:

